class SeverityEngine:
    """
    SOC Risk Scoring Engine
    Full scoring for all 350 threats in the dataset.
    """

    def __init__(self):
        self.scores = self._load_scores()

    def _load_scores(self):
        return {
            # ── Critical (9.0–10.0) ─────────────────────────────
            "Ransomware Execution":             10.0,
            "APT Cobalt Strike Payload":        10.0,
            "APT Kerberos Forgery":             9.9,
            "Credential Dumping":               9.8,
            "APT Credential Dumping":           9.8,
            "APT Zero-Day JavaScript":          9.8,
            "APT Cloud IAM Escalation":         9.7,
            "APT Process Hollowing":            9.7,
            "APT Registry Persistence":         9.7,
            "Mimikatz Usage":                   9.6,
            "Privilege Escalation":             9.5,
            "APT Supply Chain Compromise":      9.5,
            "APT Obfuscated PowerShell":        9.5,
            "APT RDP Tunneling":                9.5,
            "APT CloudTrail Evasion":           9.5,
            "APT CloudTrail Tampering":         9.5,
            "PowerShell Abuse":                 9.4,
            "APT Living Off the Land":          9.4,
            "APT Cloud Credential Theft":       9.4,
            "Kerberos Golden Ticket":           9.4,
            "APT Kerberos Silver Ticket":       9.4,
            "APT Kerberos Pass-the-Ticket":     9.4,
            "APT WMI Persistence":              9.3,
            "APT HTTPS Reverse Shell":          9.3,
            "APT Encrypted C2 Channel":         9.3,
            "APT DNS Beaconing":                9.2,
            "APT HTTPS Beaconing":              9.2,
            "APT Cloud API Abuse":              9.2,
            "Lateral Movement":                 9.2,
            "APT RDP Session Hijacking":        9.2,
            "Process Hollowing":                9.1,
            "APT Process Injection":            9.1,
            "APT Obfuscated Python":            9.1,
            "APT SMB Lateral Movement":         9.1,
            "APT Obfuscated PowerShell Loader": 9.1,
            "Token Impersonation":              9.0,
            "APT S3 Bucket Takeover":           9.0,
            "APT EKS Cluster Compromise":       9.0,
            "IAM Role Escalation":              9.0,
            "Zero-Day Exploit Attempt":         9.0,

            # ── High (7.0–8.9) ───────────────────────────────────
            "Cobalt Strike Beacon":             8.9,
            "APT DNS Tunneling":                8.9,
            "APT QUIC C2 Channel":              8.9,
            "APT CloudFormation Backdoor":      8.8,
            "APT Lambda Persistence":           8.8,
            "APT Cloud S3 Exfiltration":        8.8,
            "Persistence":                      8.8,
            "APT Malicious Rust Binary":        8.7,
            "APT Malicious Go Binary":          8.7,
            "APT Malicious PHP Backdoor":       8.7,
            "APT Malicious PHP Payload":        8.7,
            "APT Malicious WebAssembly":        8.7,
            "Malicious PowerShell Script":      8.6,
            "APT Obfuscated VBScript":          8.6,
            "APT Obfuscated JavaScript Payload":8.6,
            "APT Malicious NPM Module":         8.6,
            "APT Malicious PyPI Package":       8.6,
            "APT Malicious Electron App":       8.6,
            "Rootkit Detection":                8.5,
            "Fileless Malware":                 8.5,
            "Defense Evasion":                  8.7,
            "APT CloudWatch Evasion":           8.5,
            "Rogue Process Injection":          8.5,
            "Encrypted C2 Channel":             8.5,
            "APT Cloud KMS Abuse":              8.5,
            "APT DynamoDB Data Theft":          8.5,
            "APT SQS Queue Abuse":              8.5,
            "APT SNS Topic Abuse":              8.5,
            "APT Route53 Domain Hijack":        8.5,
            "WMI Event Subscription":           8.4,
            "Malware Persistence":              8.4,
            "Command and Control":              8.4,
            "APT Malicious Kotlin Binary":      8.4,
            "APT Malicious Swift Binary":       8.4,
            "APT Malicious Bash Script":        8.4,
            "APT Malicious Go Module":          8.4,
            "APT Malicious Rust Crate":         8.4,
            "Malicious DLL Loading":            8.3,
            "Web Shell Detection":              8.3,
            "Backdoor Communication":           8.3,
            "Non-Standard Port C2":             8.3,
            "APT gRPC C2 Channel":              8.3,
            "APT MQTT C2 Channel":              8.3,
            "APT AMQP C2 Channel":              8.3,
            "APT Redis C2 Channel":             8.3,
            "APT CoAP C2 Channel":              8.3,
            "Container Escape Attempt":         8.3,
            "Kubernetes RBAC Misconfiguration": 8.2,
            "APT DNS over HTTPS":               8.2,
            "APT DNS over TLS":                 8.2,
            "Lateral Movement SMB":             8.2,
            "SMB Worm Propagation":             8.2,
            "Tor Network Usage":                8.1,
            "Tor Exit Node Traffic":            8.1,
            "APT WebSocket C2":                 8.1,
            "Malware Dropper":                  8.1,
            "Remote Code Execution":            8.1,
            "Exploit Kit Activity":             8.0,
            "Malicious Browser Extension":      8.0,
            "Malicious Chrome Extension":       8.0,
            "CloudTrail Log Deletion":          8.0,
            "APT Cloud IAM Escalation":         8.0,
            "APT ELB Backdoor":                 8.0,
            "Serverless Backdoor":              8.0,
            "Exploit Payload Delivery":         7.9,
            "Malicious Macro Execution":        7.9,
            "Malicious Office Macro":           7.9,
            "Malicious VBS Script":             7.9,
            "Obfuscated PowerShell Script":     7.9,
            "Obfuscated VBScript":              7.9,
            "Obfuscated PHP Backdoor":          7.9,
            "Obfuscated JavaScript Loader":     7.8,
            "Malicious JavaScript Payload":     7.8,
            "Malicious Python Script":          7.8,
            "Malicious HTML Application":       7.8,
            "Malicious MSI Installer":          7.8,
            "Malicious ELF Binary":             7.7,
            "Malicious JAR File":               7.7,
            "Malicious APK File":               7.7,
            "Malicious Rust Binary":            7.7,
            "Malicious Go Binary":              7.7,
            "Malicious TypeScript Payload":     7.7,
            "Malicious Swift Binary":           7.6,
            "Malicious Kotlin Binary":          7.6,
            "Malicious Lua Script":             7.6,
            "Malicious R Script":               7.6,
            "Malicious Ruby Script":            7.6,
            "Malicious MATLAB Script":          7.6,
            "Malicious Perl Script":            7.6,
            "Malicious PHP Payload":            7.6,
            "Malicious GraphQL Query":          7.5,
            "Malicious Docker Container":       7.5,
            "Adversarial AI Payload":           7.5,
            "Malicious WebAssembly":            7.5,
            "Malicious WASM Module":            7.5,
            "Malicious NPM Package":            7.5,
            "Malicious PyPI Package":           7.5,
            "Malicious Bash Script":            7.4,
            "Malicious Batch Script":           7.4,
            "Malicious Shell Script":           7.4,
            "Malicious PHP Backdoor":           7.4,
            "Malicious Electron App":           7.4,
            "Malicious Browser Plugin":         7.4,
            "Keylogger Activity":               7.3,
            "Spyware Activity":                 7.3,
            "Adware Injection":                 7.2,
            "Suspicious Login":                 7.2,
            "Credential Harvesting Form":       7.2,
            "Kerberos Ticket Theft":            7.2,
            "Living Off the Land Binary Abuse": 7.2,
            "APT Malicious Python Package":     7.2,
            "APT Malicious TypeScript":         7.2,
            "APT Malicious Lua Script":         7.2,
            "APT Malicious R Script":           7.2,
            "APT Malicious MATLAB Script":      7.2,
            "APT Malicious Perl Script":        7.2,
            "APT Malicious Ruby Script":        7.2,
            "APT Malicious Bash Payload":       7.2,
            "APT Malicious PHP Payload":        7.1,
            "APT Malicious PowerShell Module":  7.1,
            "APT Malicious WebSocket":          7.1,
            "APT Malicious JavaScript Payload": 7.0,
            "APT Malicious VBScript":           7.0,

            # ── Impact threats ────────────────────────────────────
            "Impact: Disk Wipe":                9.3,
            "Impact: Shadow Copy Deletion":     9.2,
            "Impact: Ransomware Encryption":    10.0,
            "Impact: Cloud Data Deletion":      9.1,
            "Impact: File Encryption":          9.0,
            "Impact: System Shutdown":          8.5,
            "Impact: Cloud Instance Termination":8.5,
            "Impact: Registry Corruption":      8.3,
            "Impact: Data Overwrite":           8.8,
            "Impact: Cloud Snapshot Deletion":  8.5,
            "Impact: Service Disruption":       8.0,
            "Impact: CloudTrail Log Deletion":  8.2,
            "Impact: File Deletion":            7.5,
            "Impact: Cloud KMS Key Deletion":   8.8,
            "Impact: Boot Configuration Corruption":8.7,
            "Impact: Cloud RDS Instance Deletion":8.5,
            "Impact: MBR Overwrite":            9.2,
            "Impact: Cloud Lambda Function Deletion":8.0,
            "Impact: Process Termination":      7.8,
            "Impact: Cloud EKS Cluster Deletion":8.5,
            "Impact: Log File Deletion":        7.5,
            "Impact: Cloud S3 Object Deletion": 8.0,
            "Impact: Disk Partition Wipe":      9.0,
            "Impact: Cloud VPC Deletion":       8.5,
            "Impact: Service Account Disruption":7.8,
            "Impact: Cloud IAM Policy Deletion":8.5,
            "Impact: File System Corruption":   8.8,
            "Impact: Cloud SNS Topic Deletion": 7.8,
            "Impact: Backup Deletion":          8.8,
            "Impact: Cloud SQS Queue Deletion": 7.8,
            "Impact: Network Disruption":       8.3,
            "Impact: Cloud Route53 Record Deletion":8.0,
            "Impact: Crypto Mining Overload":   7.5,
            "Impact: Cloud DynamoDB Table Deletion":8.5,

            # ── Discovery threats ─────────────────────────────────
            "Discovery: Whoami Execution":      5.5,
            "Discovery: Netstat Recon":         5.5,
            "Discovery: System Info Gathering": 5.8,
            "Discovery: Network Share Enumeration":6.0,
            "Discovery: Active Directory Query":6.5,
            "Discovery: ARP Cache Scan":        5.5,
            "Discovery: Process Enumeration":   5.5,
            "Discovery: Cloud Instance Metadata":6.5,
            "Discovery: Installed Software Query":5.5,
            "Discovery: Network Configuration": 5.5,
            "Discovery: User Account Enumeration":6.0,
            "Discovery: Cloud Role Enumeration":6.5,
            "Discovery: Firewall Rules Query":  5.8,
            "Discovery: Remote System Scan":    6.2,
            "Discovery: Security Software Check":6.0,
            "Discovery: Cloud Resource Enumeration":6.5,
            "Discovery: Group Membership Query":5.8,
            "Discovery: DNS Server Query":      5.5,
            "Discovery: Registry Enumeration":  5.8,
            "Discovery: Cloud Storage Scan":    6.2,
            "Discovery: Service Enumeration":   5.5,
            "Discovery: File System Recon":     5.8,
            "Discovery: Network Port Scan":     6.5,
            "Discovery: Cloud API Discovery":   6.2,
            "Discovery: Local Admin Enumeration":6.5,
            "Discovery: Browser Bookmark Scan": 5.5,
            "Discovery: Cloud Key Enumeration": 6.8,
            "Discovery: Scheduled Task Query":  5.5,
            "Discovery: Cloud Policy Enumeration":6.5,
            "Discovery: Environment Variable Scan":5.5,
            "Discovery: Cloud Security Group Scan":6.2,
            "Discovery: WMI System Info":       5.8,
            "Discovery: Cloud VPC Enumeration": 6.2,

            # ── Lateral Movement threats ──────────────────────────
            "Lateral Movement: PS Remoting":    8.0,
            "Lateral Movement: WMI Execution":  8.2,
            "Lateral Movement: SMB File Copy":  7.8,
            "Lateral Movement: RDP Session":    8.0,
            "Lateral Movement: WinRM Abuse":    8.0,
            "Lateral Movement: SSH Tunneling":  7.8,
            "Lateral Movement: DCOM Execution": 7.9,
            "Lateral Movement: PsExec Usage":   8.3,
            "Lateral Movement: Cloud Instance SSH":7.5,
            "Lateral Movement: SMB Admin Share":8.0,
            "Lateral Movement: Remote Service Creation":8.2,
            "Lateral Movement: Cloud API Lateral":7.8,
            "Lateral Movement: RDP Hijacking":  8.5,
            "Lateral Movement: WMI Remote Process":8.0,
            "Lateral Movement: Cloud Role Assumption":7.8,
            "Lateral Movement: Pass-the-Hash":  8.8,
            "Lateral Movement: SMB Named Pipe": 7.8,
            "Lateral Movement: Cloud Instance Metadata Abuse":7.5,
            "Lateral Movement: Remote Desktop Protocol":8.0,
            "Lateral Movement: Kerberos Service Ticket":8.2,
            "Lateral Movement: Cloud Lambda Invoke":7.5,
            "Lateral Movement: Remote Registry Access":7.8,
            "Lateral Movement: SSH Key Abuse":  7.8,
            "Lateral Movement: Cloud ECS Task Run":7.5,
            "Lateral Movement: Remote PowerShell Session":8.0,
            "Lateral Movement: SMB File Transfer":7.8,
            "Lateral Movement: Cloud IAM Role Abuse":8.0,
            "Lateral Movement: Remote Task Execution":8.0,
            "Lateral Movement: Cloud EKS Pod Lateral":7.8,
            "Lateral Movement: NTLM Relay Attack":8.5,
            "Lateral Movement: Remote WMI Query":7.8,
            "Lateral Movement: Cloud S3 Lateral Access":7.5,
            "Lateral Movement: RDP Shadowing":  8.0,
        }

    def calculate(self, dataframe):
        dataframe["risk_score"] = dataframe["threat"].apply(self._risk_score)
        dataframe["severity"]   = dataframe["risk_score"].apply(self._severity)
        return dataframe

    def _risk_score(self, threat):
        return self.scores.get(threat, 6.5)

    def _severity(self, score):
        if score >= 9.0: return "Critical"
        if score >= 7.0: return "High"
        if score >= 4.0: return "Medium"
        return "Low"